name: go_test

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 14 * * *'
jobs:
  run_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.18', '1.19', '1.20', '1.21', '1.22', '1.23', '1.24' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Test
        run: |
          for ((i=1; i<=3; i++))
          do
            go test -count=1 -run Test_.+ -timeout 12s ./...
            echo "Test $i done"
          done

      - name: Test_ARM64
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          base_image: golang:${{ matrix.go-version }}
          run: |
            for ((i=1; i<=3; i++))
            do
              go test -count=1 -run Test_.+ -timeout 20s ./...
              echo "Test $i done"
            done

      - name: Test_ARM32
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: armv7
          base_image: golang:${{ matrix.go-version }}
          run: |
            for ((i=1; i<=3; i++))
            do
              go test -count=1 -run Test_.+ -timeout 20s ./...
              echo "Test $i done"
            done